exports.getAddress = require("./get-address")
exports.storeAll = require("./filecoin-market-consumer/store-all")
exports.makeDealProposal = require("./deal-client/make-deal-proposal")
exports.getDealProposal = require("./deal-client/get-deal-proposal")
exports.getDealId = require("./deal-client/get-deal-id")