exports.getAddress = require("./get-address")
exports.storeAll = require("./filecoin-market-consumer/store-all")
exports.makeDealProposal = require("./deal-client/start-backup")
exports.getDealProposal = require("./deal-client/get-deals")
exports.getDealProposal = require("./deal-client/get-commp")
exports.getDealId = require("./deal-client/get-backup-item")